version: "3"
services:
  consumer:
    image: consumer

    depends_on:
     - rabbit
     - mongo
    #command: ["./wait-for-it.sh", "db:5432", "--", "python", "consumer.py"]

    networks:
      - backend

  rabbit:
    image: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

    ports:
      - "5672:5672"

    networks:
      - backend

  mongo:
    image: mongo

    depends_on:
     - rabbit

    ports:
      - "27017:27017"

#    volumes:
#    - /Users/clumpy/docker/mongodb:/mongo/db

    environment:
      MONGODB_USERNAME: "myusername"
      MONGODB_PASSWORD: "mypassword"
      MONGODB_DATEBASE: "test-database"

    networks:
      - backend
networks:
  backend: