version: "3"
services:
  consumer:
    image: consumer

    depends_on:
     - rabbit
    #command: ["./wait-for-it.sh", "db:5432", "--", "python", "consumer.py"]

    networks:
      - webnet
  rabbit:
    image: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"

    ports:
      - "5672:5672"

    networks:
      - webnet
#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - "/home/docker/data:/data"
#    networks:
#      - webnet
networks:
  webnet: