version: "3"

services:
  app:
    build: mysite
    command: bash -c "sleep 30 && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000